env:
 browser: true
 es6: true
extends:
 - airbnb-base
 - plugin:import/errors
 - plugin:import/warnings
 - plugin:import/typescript
globals:
 Atomics: readonly
 SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
 ecmaVersion: 2016
 sourceType: module
plugins:
 - '@typescript-eslint'
rules:
 no-unused-vars: 0
 '@typescript-eslint/no-unused-vars': 2
 import/no-unresolved: [2, {commonjs: true, amd: true}]
 import/named: 2
 import/namespace: 2
 import/default: 2
 import/export: 2
 import/extensions:
   - 'error'
   - ignorePackages
   - ts: 'never'