version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mongo:
    image: "mongo:bionic"
    ports:
      - "27017:27017"
  web:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - EMAIL_ADDRESS
      - EMAIL_PASSWORD
      - EBAY_CLIENT_ID
      - EBAY_CLIENT_SECRET